aggregating:
  build: aggregating/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9992:9992
    - 8992:8992

maturing:
  build: maturing/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9993:9993
    - 8993:8993

bottling:
  build: bottling/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9994:9994
    - 8994:8994

presenting:
  build: presenting/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9991:9991
    - 8991:8991

zuul:
  build: zuul/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9995:9995
    - 8995:8995

ingredients:
  build: ingredients/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9996:9996
    - 8996:8996

reporting:
  build: reporting/build/docker
  environment:
    spring.profiles.active: eureka
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9997:9997
    - 8997:8997

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

discovery:
  build: eureka/build/docker
  ports:
    - 8761:8761

rabbitmq:
  image: rabbitmq:management
  expose:
    - 5672
    - 15672


